version:  '3.7'

services:
  mariaTodo:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: pwd
    ports:
     - 3306

    volumes:
     - ./mariaTodo/mysql:/var/lib/mysql
     - ./scripts.dir:/scripts.dir
     - ./mariaTodo/backups:/backups


  mariaUser:
    image: mariadb:10.4
    restart: on-failure
    environment:
      MYSQL_ROOT_PASSWORD: pwd
    ports:
     - 3307

    volumes:
     - ./mariaUser/mysql:/var/lib/mysql
     - ./scripts.dir:/scripts.dir
     - ./mariaUser/backups:/backups
